export const socketUrl = '//localhost:8080';
export const title = 'URF Stats';
export const urls = {
    base: 'http://ddragon.leagueoflegends.com/cdn/',
    version: '5.6.2',
    splash: function(championName, num) {
        return `${urls.base}img/champion/splash/${toTitleCase(championName)}_${num || 0}.jpg`;
    },
    loading: function(championName, num) {
        return `${urls.base}img/champion/loading/${toTitleCase(championName)}_${num || 0}.jpg`;
    },
    square: function(championName) {
        return `${urls.base}${urls.version}/img/champion/${championName}.png`;
    },
    matchDetails: function(region, matchId) {
        if (region === 'EUNE') region = 'EUN';
        if (region === 'LAN') region = 'LA1';
        if (region === 'LAS') region = 'LA2';
        if (region === 'OCE') region = 'OC1';
        return `http://matchhistory.${region}.leagueoflegends.com/` +
        `en/#match-details/${region.toUpperCase()}1/${matchId}`;
    }
};
export const toTitleCase = (str) => {
    return str.replace(/\w\S*/g, (txt) => {
        return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
    });
};
export const championNames = {
    "Shaco": "Shaco",
    "DrMundo": "Dr. Mundo",
    "Rammus": "Rammus",
    "Anivia": "Anivia",
    "Irelia": "Irelia",
    "Yasuo": "Yasuo",
    "Sona": "Sona",
    "Kassadin": "Kassadin",
    "Zac": "Zac",
    "Gnar": "Gnar",
    "Karma": "Karma",
    "Corki": "Corki",
    "Gangplank": "Gangplank",
    "Janna": "Janna",
    "Braum": "Braum",
    "Ashe": "Ashe",
    "Tryndamere": "Tryndamere",
    "Jax": "Jax",
    "Morgana": "Morgana",
    "Zilean": "Zilean",
    "Singed": "Singed",
    "Evelynn": "Evelynn",
    "Twitch": "Twitch",
    "Galio": "Galio",
    "Velkoz": "Vel'Koz",
    "Olaf": "Olaf",
    "Annie": "Annie",
    "Leblanc": "LeBlanc",
    "Karthus": "Karthus",
    "Urgot": "Urgot",
    "Amumu": "Amumu",
    "XinZhao": "Xin Zhao",
    "Chogath": "Cho'Gath",
    "TwistedFate": "Twisted Fate",
    "FiddleSticks": "Fiddle Sticks",
    "Vladimir": "Vladimir",
    "Warwick": "Warwick",
    "Teemo": "Teemo",
    "Tristana": "Tristana",
    "Sivir": "Sivir",
    "Soraka": "Soraka",
    "Ryze": "Ryze",
    "Sion": "Sion",
    "MasterYi": "Master Yi",
    "Alistar": "Alistar",
    "MissFortune": "Miss Fortune",
    "Nunu": "Nunu",
    "Rengar": "Rengar",
    "Volibear": "Volibear",
    "Fizz": "Fizz",
    "Graves": "Graves",
    "Ahri": "Ahri",
    "Lux": "Lux",
    "Shyvana": "Shyvana",
    "Xerath": "Xerath",
    "Thresh": "Thresh",
    "Shen": "Shen",
    "Jinx": "Jinx",
    "KogMaw": "Kog'Maw",
    "Riven": "Riven",
    "Talon": "Talon",
    "Malzahar": "Malzahar",
    "Kalista": "Kalista",
    "Kayle": "Kayle",
    "RekSai": "Rek'Sai",
    "Leona": "Leona",
    "Gragas": "Gragas",
    "Lulu": "Lulu",
    "Fiora": "Fiora",
    "Poppy": "Poppy",
    "Ziggs": "Ziggs",
    "Udyr": "Udyr",
    "Viktor": "Viktor",
    "Sejuani": "Sejuani",
    "Varus": "Varus",
    "Nautilus": "Nautilus",
    "Draven": "Draven",
    "Bard": "Bard",
    "Mordekaiser": "Mordekaiser",
    "Yorick": "Yorick",
    "Pantheon": "Pantheon",
    "Ezreal": "Ezreal",
    "Garen": "Garen",
    "Akali": "Akali",
    "Kennen": "Kennen",
    "Vayne": "Vayne",
    "Jayce": "Jayce",
    "Cassiopeia": "Cassiopeia",
    "Lissandra": "Lissandra",
    "Rumble": "Rumble",
    "Khazix": "Kha'Zix",
    "Darius": "Darius",
    "Hecarim": "Hecarim",
    "Skarner": "Skarner",
    "Lucian": "Lucian",
    "Heimerdinger": "Heimerdinger",
    "Nasus": "Nasus",
    "Zed": "Zed",
    "Nidalee": "Nidalee",
    "Syndra": "Syndra",
    "Quinn": "Quinn",
    "JarvanIV": "Jarvan IV",
    "Renekton": "Renekton",
    "Maokai": "Maokai",
    "Nocturne": "Nocturne",
    "Katarina": "Katarina",
    "LeeSin": "LeeSin",
    "MonkeyKing": "Wukong",
    "Brand": "Brand",
    "Azir": "Azir",
    "Nami": "Nami",
    "Elise": "Elise",
    "Diana": "Diana",
    "Orianna": "Orianna",
    "Aatrox": "Aatrox",
    "Zyra": "Zyra",
    "Trundle": "Trundle",
    "Veigar": "Veigar",
    "Taric": "Taric",
    "Caitlyn": "Caitlyn",
    "Blitzcrank": "Blitzcrank",
    "Malphite": "Malphite",
    "Vi": "Vi",
    "Swain": "Swain"
};
