const _ = require('lodash');
export const pluckAll = (array, props) => {
    return _.map(array, function(obj) { return _.pick(obj, ...props); });
};

export const rand = num => Math.floor(Math.random() * (num - 1));
export const title = 'URF Stats';
export const urls = {
    base: 'http://ddragon.leagueoflegends.com/cdn/',
    version: '5.6.2',
    splash: function(championName, num) {
        return `${urls.base}img/champion/splash/${(championName)}_${num || 0}.jpg`;
    },
    loading: function(championName, num) {
        return `${urls.base}img/champion/loading/${(championName)}_${num || 0}.jpg`;
    },
    square: function(championName) {
        return `${urls.base}${urls.version}/img/champion/${championName}.png`;
    },
    item: function(itemId) {
        return `${urls.base}${urls.version}/img/item/${itemId}.png`;
    },
    matchDetails: function(region, matchId) {
        var short = region + '1';
        if (region === 'EUNE') short = 'EUN1';
        if (region === 'LAN') short = 'LA1';
        if (region === 'LAS') short = 'LA2';
        if (region === 'OCE') short = 'OC1';
        return `http://matchhistory.${region}.leagueoflegends.com/` +
        `en/#match-details/${short.toUpperCase()}/${matchId}`;
    }
};
export const toTitleCase = (str) => {
    return str.replace(/\w\S*/g, (txt) => {
        return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
    });
};
export const formatNumber = (num) => {
    // fixed to 2 digits, but drop trailing zeros
    if (num >= 1e9) {
        return Number((num / 1e9).toFixed(2)) + 'b';
    } else if (num >= 1e6) {
        return Number((num / 1e6).toFixed(2)) + 'm';
    } else if (num >= 1e3) {
        return Number((num / 1e3).toFixed(2)) + 'k';
    } else {
        return num;
    }
};
export const championNames = {
    "Aatrox": "Aatrox",
    "Ahri": "Ahri",
    "Akali": "Akali",
    "Alistar": "Alistar",
    "Amumu": "Amumu",
    "Anivia": "Anivia",
    "Annie": "Annie",
    "Ashe": "Ashe",
    "Azir": "Azir",
    "Bard": "Bard",
    "Blitzcrank": "Blitzcrank",
    "Brand": "Brand",
    "Braum": "Braum",
    "Caitlyn": "Caitlyn",
    "Cassiopeia": "Cassiopeia",
    "Chogath": "Cho'Gath",
    "Corki": "Corki",
    "Darius": "Darius",
    "Diana": "Diana",
    "Draven": "Draven",
    "DrMundo": "Dr. Mundo",
    "Elise": "Elise",
    "Evelynn": "Evelynn",
    "Ezreal": "Ezreal",
    "FiddleSticks": "Fiddle Sticks",
    "Fiora": "Fiora",
    "Fizz": "Fizz",
    "Galio": "Galio",
    "Gangplank": "Gangplank",
    "Garen": "Garen",
    "Gnar": "Gnar",
    "Gragas": "Gragas",
    "Graves": "Graves",
    "Hecarim": "Hecarim",
    "Heimerdinger": "Heimerdinger",
    "Irelia": "Irelia",
    "Janna": "Janna",
    "JarvanIV": "Jarvan IV",
    "Jax": "Jax",
    "Jayce": "Jayce",
    "Jinx": "Jinx",
    "Kalista": "Kalista",
    "Karma": "Karma",
    "Karthus": "Karthus",
    "Kassadin": "Kassadin",
    "Katarina": "Katarina",
    "Kayle": "Kayle",
    "Kennen": "Kennen",
    "Khazix": "Kha'Zix",
    "KogMaw": "Kog'Maw",
    "Leblanc": "LeBlanc",
    "LeeSin": "LeeSin",
    "Leona": "Leona",
    "Lissandra": "Lissandra",
    "Lucian": "Lucian",
    "Lulu": "Lulu",
    "Lux": "Lux",
    "Malphite": "Malphite",
    "Malzahar": "Malzahar",
    "Maokai": "Maokai",
    "MasterYi": "Master Yi",
    "MissFortune": "Miss Fortune",
    "MonkeyKing": "Wukong",
    "Mordekaiser": "Mordekaiser",
    "Morgana": "Morgana",
    "Nami": "Nami",
    "Nasus": "Nasus",
    "Nautilus": "Nautilus",
    "Nidalee": "Nidalee",
    "Nocturne": "Nocturne",
    "Nunu": "Nunu",
    "Olaf": "Olaf",
    "Orianna": "Orianna",
    "Pantheon": "Pantheon",
    "Poppy": "Poppy",
    "Quinn": "Quinn",
    "Rammus": "Rammus",
    "RekSai": "Rek'Sai",
    "Renekton": "Renekton",
    "Rengar": "Rengar",
    "Riven": "Riven",
    "Rumble": "Rumble",
    "Ryze": "Ryze",
    "Sejuani": "Sejuani",
    "Shaco": "Shaco",
    "Shen": "Shen",
    "Shyvana": "Shyvana",
    "Singed": "Singed",
    "Sion": "Sion",
    "Sivir": "Sivir",
    "Skarner": "Skarner",
    "Sona": "Sona",
    "Soraka": "Soraka",
    "Swain": "Swain",
    "Syndra": "Syndra",
    "Talon": "Talon",
    "Taric": "Taric",
    "Teemo": "Teemo",
    "Thresh": "Thresh",
    "Tristana": "Tristana",
    "Trundle": "Trundle",
    "Tryndamere": "Tryndamere",
    "TwistedFate": "Twisted Fate",
    "Twitch": "Twitch",
    "Udyr": "Udyr",
    "Urgot": "Urgot",
    "Varus": "Varus",
    "Vayne": "Vayne",
    "Veigar": "Veigar",
    "Velkoz": "Vel'Koz",
    "Vi": "Vi",
    "Viktor": "Viktor",
    "Vladimir": "Vladimir",
    "Volibear": "Volibear",
    "Warwick": "Warwick",
    "Xerath": "Xerath",
    "XinZhao": "Xin Zhao",
    "Yasuo": "Yasuo",
    "Yorick": "Yorick",
    "Zac": "Zac",
    "Zed": "Zed",
    "Ziggs": "Ziggs",
    "Zilean": "Zilean",
    "Zyra": "Zyra"
};

// Ran
// lolapi.Static.getChampions({champData: ['skins']}, (error, result) => {
//     Object.keys(result.data).map((r) => {
//         console.log(result.data[r].key + ',' + result.data[r].skins.length);
//     });
// });
export const numSkins = {
    'Aatrox': 3,
    'Ahri': 6,
    'Akali': 8,
    'Alistar': 8,
    'Amumu': 9,
    'Anivia': 6,
    'Annie': 10,
    'Ashe': 8,
    'Azir': 2,
    'Bard': 2,
    'Blitzcrank': 8,
    'Brand': 5,
    'Braum': 3,
    'Caitlyn': 7,
    'Cassiopeia': 5,
    'Chogath': 6,
    'Corki': 8,
    'Darius': 5,
    'Diana': 3,
    'Draven': 4,
    'DrMundo': 8,
    'Elise': 4,
    'Evelynn': 5,
    'Ezreal': 8,
    'FiddleSticks': 8,
    'Fiora': 4,
    'Fizz': 5,
    'Galio': 6,
    'Gangplank': 7,
    'Garen': 7,
    'Gnar': 2,
    'Gragas': 9,
    'Graves': 6,
    'Hecarim': 5,
    'Heimerdinger': 6,
    'Irelia': 5,
    'Janna': 7,
    'JarvanIV': 7,
    'Jax': 9,
    'Jayce': 3,
    'Jinx': 3,
    'Kalista': 2,
    'Karma': 5,
    'Karthus': 6,
    'Kassadin': 5,
    'Katarina': 9,
    'Kayle': 8,
    'Kennen': 6,
    'Khazix': 3,
    'KogMaw': 9,
    'Leblanc': 5,
    'LeeSin': 7,
    'Leona': 5,
    'Lissandra': 3,
    'Lulu': 5,
    'Lux': 6,
    'Malphite': 7,
    'Malzahar': 6,
    'Maokai': 6,
    'MasterYi': 6,
    'MissFortune': 8,
    'MonkeyKing': 5,
    'Mordekaiser': 5,
    'Morgana': 7,
    'Nami': 4,
    'Nasus': 7,
    'Nautilus': 5,
    'Nidalee': 8,
    'Nocturne': 6,
    'Nunu': 7,
    'Olaf': 5,
    'Orianna': 6,
    'Pantheon': 7,
    'Poppy': 7,
    'Quinn': 3,
    'Rammus': 8,
    'RekSai': 2,
    'Renekton': 7,
    'Riven': 6,
    'Rumble': 4,
    'Ryze': 9,
    'Sejuani': 6,
    'Shaco': 7,
    'Shen': 7,
    'Shyvana': 6,
    'Singed': 7,
    'Sion': 5,
    'Skarner': 5,
    'Sona': 7,
    'Soraka': 6,
    'Swain': 4,
    'Syndra': 3,
    'Talon': 4,
    'Taric': 4,
    'Teemo': 9,
    'Thresh': 4,
    'Tristana': 7,
    'Trundle': 5,
    'Tryndamere': 7,
    'TwistedFate': 9,
    'Twitch': 7,
    'Udyr': 5,
    'Urgot': 4,
    'Varus': 5,
    'Vayne': 7,
    'Veigar': 9,
    'Velkoz': 3,
    'Vi': 4,
    'Viktor': 4,
    'Vladimir': 7,
    'Volibear': 5,
    'Warwick': 9,
    'Xerath': 5,
    'XinZhao': 7,
    'Yasuo': 3,
    'Yorick': 3,
    'Zac': 2,
    'Zed': 3,
    'Ziggs': 5,
    'Zilean': 5,
    'Zyra': 4
}
